version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"


  email_worker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq

    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq/
    command: ["python", "app/services/email_worker.py"]

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"